package com.example.sprite.Controllers;

import android.graphics.Bitmap;
import android.graphics.Color;

import androidx.annotation.Nullable;

import com.example.sprite.Models.Event;
import com.google.zxing.BarcodeFormat;
import com.google.zxing.BinaryBitmap;
import com.google.zxing.ChecksumException;
import com.google.zxing.FormatException;
import com.google.zxing.NotFoundException;
import com.google.zxing.Result;
import com.google.zxing.WriterException;
import com.google.zxing.common.BitMatrix;
import com.google.zxing.qrcode.QRCodeReader;
import com.google.zxing.qrcode.QRCodeWriter;

/**
 * Service class responsible for generating and decoding QR codes that are
 * associated with {@link Event} objects.
 *
 * The QR codes generated by this class encode a simple text payload of
 * the form:
 *
 *      SPRITE_EVENT:<eventId>
 *
 * where <eventId> is the unique identifier of the event in Firestore.
 */
public class QRCodeService {


    private static final String EVENT_PREFIX = "SPRITE_EVENT:";

    private final QRCodeWriter qrCodeWriter;
    private final QRCodeReader qrCodeReader;

    public QRCodeService() {
        this.qrCodeWriter = new QRCodeWriter();
        this.qCodeReader = new QRCodeReader();
    }

    /**
     * Builds the text payload that will be encoded into the QR code for the
     * given event.
     *
     * @param event the event to encode
     * @return a String of the form "SPRITE_EVENT:<eventId>"
     * @throws IllegalArgumentException if the event or its id is null
     */
    public String buildEventPayload(Event event) {
        if (event == null || event.getEventId() == null) {
            throw new IllegalArgumentException("Event or eventId is null");
        }
        return EVENT_PREFIX + event.getEventId();
    }

    /**
     * Generates a QR code bitmap for the given event.
     *
     * @param event the event whose id should be encoded
     * @param size  the width and height of the resulting square bitmap, in pixels
     * @return the generated QR code as a Bitmap
     * @throws WriterException          if the underlying ZXing writer fails
     * @throws IllegalArgumentException if event or id is null
     */
    public Bitmap generateEventQRCode(Event event, int size) throws WriterException {
        String payload = buildEventPayload(event);
        BitMatrix bitMatrix =
                qrCodeWriter.encode(payload, BarcodeFormat.QR_CODE, size, size);

        Bitmap bitmap = Bitmap.createBitmap(size, size, Bitmap.Config.RGB_565);
        for (int x = 0; x < size; x++) {
            for (int y = 0; y < size; y++) {
                bitmap.setPixel(x, y,
                        bitMatrix.get(x, y) ? Color.BLACK : Color.WHITE);
            }
        }
        return bitmap;
    }

    /**
     * Attempts to extract an event id from a decoded QR content string.
     *
     * @param content the raw text content read from a QR code
     * @return the event id if the content matches the SPRITE_EVENT format,
     *         or {@code null} otherwise
     */
    @Nullable
    public String parseEventIdFromContent(String content) {
        if (content == null) return null;
        if (content.startsWith(EVENT_PREFIX)) {
            return content.substring(EVENT_PREFIX.length());
        }
        return null;
    }

    /**
     * Decodes a BinaryBitmap produced by a camera scanner and, if it is a
     * SPRITE event QR, extracts the associated event id.
     */
    @Nullable
    public String decodeEventIdFromBinaryBitmap(BinaryBitmap image)
            throws ChecksumException, NotFoundException, FormatException {
        Result result = qrCodeReader.decode(image);
        return parseEventIdFromContent(result.getText());
    }

    /**
     * Original skeleton method kept for backwards-compatibility with any
     * existing call sites. It simply decodes the QR code but does not return
     * the result. Prefer using {@link #decodeEventIdFromBinaryBitmap(BinaryBitmap)}
     * in new code.
     */
    public void decodeQRCode(BinaryBitmap image)
            throws ChecksumException, NotFoundException, FormatException {
        qrCodeReader.decode(image);
    }
}
